language: rust
sudo: false
cache:
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target

addons:
  apt:
    packages:
    - asciidoc

rust:
- nightly
- beta
- stable

script:
- make
- make test
