language: rust
sudo: false
cache:
  directories:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target

addons:
  apt:
    packages:
    - pandoc

rust:
- nightly
- beta
- stable

script:
- cargo build --verbose
- RUST_BACKTRACE=1 cargo test --verbose --all
