language: rust
sudo: false
cache: cargo

rust:
- nightly
- beta
- stable

matrix:
  allow_failures:
    - rust: nightly
    fast_finish: true

before_install:
- rustup component add clippy

script:
- make
- make test
